spring:
  # 安全配置
  security:
    user:
      name: ENC(dgZ/yAQ91io2ZWR0ktsEzA==)     # pig
      password: ENC(dgZ/yAQ91io2ZWR0ktsEzA==) # pig
  cloud:
    nacos:
      discovery:
        server-addr: 106.13.195.5:8848